export enum Job {
  STOREKEEPER = 'STOREKEEPER',
  ADMINISTRATOR = 'ADMINISTRATOR',
  SUPER_ADMIN = 'SUPER_ADMIN',
  SERVICE_MANAGER = 'SERVICE_MANAGER',
  YOUTH_HOUSE_MANAGER = 'YOUTH_HOUSE_MANAGER',
}
